# Freezes the current main as a release in a release branch.
name: Beta Deploy
run-name: ${{ github.workflow }}. ${{ github.ref_name }} ${GITHUB_SHA::7}
on:
  workflow_dispatch:
  workflow_call:
    inputs:
      ref:
        description: "Code reference from a parent workflow"
        required: false
        type: string

jobs:
  printer:
    name: First step
    runs-on: [ubuntu-latest]
    steps:
      - name: Set outputs
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - name: First step
        run-name: ${{ github.ref_name }} (${{ steps.vars.outputs.sha_short }})
        run: echo
      - id: print
        name: Print logs
        run: |
          echo "AAAAAA"