# Freezes the current main as a release in a release branch.
name: Beta Deploy
run-name: "${{ github.workflow }}: ${{ github.ref_name }} #${{ github.sha }}"
on:
  workflow_dispatch:
  workflow_call:
    inputs:
      ref:
        description: "Code reference from a parent workflow"
        required: false
        type: string

jobs:
  printer:
    name: First step
    runs-on: [ubuntu-latest]
    steps:
      - id: print
        name: Print logs
        run: |
          echo "AAAAAA"