# Freezes the current main as a release in a release branch.
name: Freeze Release
on:
  workflow_dispatch:
    inputs:
      force:
        type: boolean
        description: Force the workflow
        default: false
        required: false

jobs:
  freeze_release:
    name: Freeze Release
    runs-on: [ubuntu-latest]
    steps:
      - id: create_branch
        name: Create Release Branch
        run: |
          # We create releases every 2 weeks
          # Plain cronjob syntax does not provide such option.
          # We need to check which week it is.

          echo " {{ inputs.force }} "

          if [ $(expr $(date +%W) % 2) -eq 1  ] || [ inputs.force = 'true' ];
          then
            version=`dart ../tools/pubspec_version.dart --major-minor --pubspec ../pubspec.yaml`

            bundle exec fastlane freeze_release

            echo " {{ }} "
          fi